# Generated by Django 4.0.3 on 2022-04-06 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('DEPARTMENT_STORE', 'DEPARTMENT STORE'), ('SUPERMARKET', 'SUPERMARKET'), ('GROCER_STORE', 'GROCER STORE'), ('GREENGROCER_STORE', 'GREENGROCER STORE'), ('BUTCHER', 'BUTCHER'), ('BAKER', 'BAKER'), ('FISHMONGER', 'FISHMONGER'), ('CHEMIST', 'CHEMIST'), ('JEWELLERY_STORE', 'JEWELLERY STORE'), ('SHOE_SHOP', 'SHOE SHOP'), ('OTHERS', 'OTHERS')], max_length=32)),
                ('photo', models.ImageField(upload_to=None)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
