# Generated by Django 4.0.3 on 2022-04-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='store',
            name='source',
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('DEPARTMENT_STORE', 'DEPARTMENT STORE'), ('SUPERMARKET', 'SUPERMARKET'), ('GROCER_STORE', 'GROCER STORE'), ('GREENGROCER_STORE', 'GREENGROCER STORE'), ('BUTCHER', 'BUTCHER'), ('BAKER', 'BAKER'), ('FISHMONGER', 'FISHMONGER'), ('CHEMIST', 'CHEMIST'), ('JEWELLERY_STORE', 'JEWELLERY STORE'), ('SHOE_SHOP', 'SHOE SHOP'), ('OTHERS', 'OTHERS')], default='SUPERMARKET', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
