# Generated by Django 4.0.3 on 2022-04-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_photo_store_image_rename_amount_store_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Not Available')], max_length=255),
        ),
    ]
