# Generated by Django 4.0.3 on 2022-04-15 10:29

from django.db import migrations, models
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_city_store_location_alter_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('SUPERMARKET', 'SUPERMARKET'), ('GROCER_STORE', 'GROCER STORE'), ('BUTCHER', 'BUTCHER'), ('BAKER', 'BAKER'), ('FISHMONGER', 'FISH MONGER'), ('CHEMIST', 'CHEMIST or PHAMARCY'), ('FASHION', 'FASHION'), ('BOOK_SHOP', 'BOOK SHOP'), ('HAIRDRESSER|BARBER', 'HAIRDRESSER & BARBER'), ('PATROL_STATION', 'PATROL STATION'), ('OTHERS', 'OTHERS')], default='FASHION', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
