# Generated by Django 4.0.4 on 2022-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_store_name_alter_store_category_alter_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
