# Generated by Django 4.0.4 on 2022-04-20 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0005_store_name_alter_store_category_alter_store_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('MOBILE MONEY', [('MTN', 'MTN'), ('ORANGE', 'Orange')]), ('BANK TRANSACTION', [('MASTER', 'Debit Card'), ('MASTER', 'Credit Card'), ('MASTER', 'Visa Card')]), ('CRYPTO CURRENCY', [('BITCOIN', 'Bitcoin'), ('PLANTICOIN', 'Planticoin')])], default='MTN', max_length=255)),
                ('date', models.DateField(null=None)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(default='SUPERMARKET', on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'ordering': ['-booked_on'],
            },
        ),
    ]
